"Core":
  - - "About"
    - - "Hello! This is a Discord chat bot designed to be useful. Hopefully.\n\nDepending on who runs this bot, \
        there could be a number of different plugins and thus features available at your disposal. Therefore, \
        this manual section is for the core functions of the bot only.\n\nYou can read the manual entries of other \
        plugins (if they are written) by using the `{invoker}manual` command and selecting a topic index, just like \
        how you did to read this entry.\n\nThe base code was written by Jsh#3741 using discord.py. If you have any \
        questions, suggestions, bug reports, code criticisms, death threats, etc., please forward them to him."

  - - "General usage"
    - - "You can invoke commands with a simple syntax: `<invoker> <base command> <parameters>`\nSo as an example: \
        `{invoker}ping is a game` results in a response of:\n\nPong!\nis a game\n\nIn this case, `{invoker}` \
        is the invoker, `ping` is the base command, and `is a game` is the parameters. **In most cases, \
        there can be multiple different invokers at any given time. An invoker that will always work would be \
        a mention to the bot name, unless the bot has been muted by a bot moderator**. \n\nThis is a very simple \
        example, but all commands follow this type of syntax. Some base commands will have multiple \
        subcommands - for example, `{invoker}base uptime` and `{invoker}base announcement` are both \
        individual commands of the base command, `base`."
          
      - "In order to figure out what syntax a particular command has, you can use the **`{invoker}help`** command. \
        Let's say you want to see more information on how the `ping` command works. `{invoker}help <base command>` \
        will get you help on the given base command, so we would want to use `{invoker}help ping` to get help on \
        the `ping` command.\n\nThe help that you are given will generally include the usage syntax of the command. \
        The syntax for `ping` is pretty easy to figure out. However, some other commands can be significantly more \
        complex. **To understand the help output, check out `{invoker}manual core 3`**.\n\nLastly, **you can edit \
        most commands**, and the bot will follow suit. For example, if the bot gives you a syntax error, you \
        can edit your command to avoid making a mess in chat. However, not all commands can be edited - if the \
        bot edits its *own* message to one of your commands, or has no response, you will be unable to edit \
        that command."

  - - "Understanding syntax"
    - - |
        Command syntax follows a few basic rules:
        
        **`bold`**: Required. This must be included for this command.
        _`italics`_: Optional.
        __`underline`__: Substitute with your own input.
        __`"quotes"`__: Include quotes if there are spaces in your input.
        
        These properties can be combined for user input. For example:
        Required user argument: __**`"input"`**__
        Optional user argument: ___`"input"`___
        Optional, and no quotes needed:  ___`input`___
        
        There can also be options with attached parameters. If you include the option, the parameter directly following it must also be included.
        This link is shown through the syntax by keeping them close together:
        `option ​`__`"attached"`__
        
        See the next page for examples.
        
      - |
        Example: **`ping`**`​　​`___`message`___
        Note: ___`message`___ is optional (italics).
        Sample: `{invoker}ping is a game`
        
        Example: **`base`**`​　​`**`join`**
        Note: **`join`** must be written as is (bold, no underline).
        Sample: `{invoker}base join`

        Example: **`help`**`​　​`_`here`_`​　​`___`base`___`​　​`___`topic`___
        Sample: `{invoker}help mod 2`
        Sample: `{invoker}help here mod toggle`
        
        Example: **`pick`**`​　​`__**`"entry 1"`**__`​　​`__**`"entry 2"`**__`​　​`___`"additional entries"`___
        Sample: `{invoker}pick Dota "League of Legends" Smite`
        Sample: `{invoker}pick pizza burger salad pasta takeout`
        Sample: `{invoker}pick homework vidya`
        
        See the next page for more examples.
        
      - |
        Example: **`tag`**`​　​`**`create`**`​　​`_`sound`_`​　​`**__`"tag name"`__**`​　​`__**`tag contents`**__
        Note: Command simplified for this example
        Sample: `{invoker}tag create sound ok https://youtu.be/oYtldnVOHc0`
        
        Example: **`wolfram`**`​　​`_`text`_`​　​`_`results ​`__`number`___`​　​`__**`query`**__
        Note: If you include the option _`results`_, you must also include its attached parameter ___`number`___
        Sample: `{invoker}wolfram capital of France`
        Sample: `{invoker}wolfram text results 1 capital of France`

        Example: **`lol`**`​　​`**`mastery`**`​　​`_`champion ​`__`"champion name"`___`​　​`__**`summoner name`**__
        Note: Like in the previous example, if you include _`champion`_, you must also include the attached parameter __`"champion name"`__
        Sample: `{invoker}lol mastery champion "master yi" c9 sneaky`
        
      - |
        Lastly, there are attachments. They look like this:
        Required: **`[Attachment: `__`input file`__`]`**
        Optional: _`[Attachment: `__`input file`__`]`_
        
        These commands use an uploaded attachment file. To call these commands, drag a file into Discord. In the "Add a comment" field, write the command.
        
        Example: **`tag`**`​　​`**`import`**`​　​`**`[Attachment: `__`tag database`__`]`**
        In order to call this command, you would first drag the tag database file into Discord, then under the "Add a comment" field, type `{invoker}tag import`
        
      - |
        Tip: Sometimes, the argument you want is also the name of an option. To ensure that the bot interprets your input as an argument, wrap it around in quotes.
        For example, `{invoker}tag create rules NSFW content is not allowed` will create an NSFW tag with the text "content is not allowed". To fix this, wrap the text in quotes: `{invoker}tag create rules "NSFW content is not allowed"`
        
        Tip: If the syntax does not suggest quotes, it likely means that the input type is a single word or number. Alternatively, if the argument is the last part of a command, it likely means that the rest of your input will be used as that one argument, so no quotes are needed (unless you run into the above situation).

  - - "Server owners"
    - - "It's important to understand how to properly configure the bot for your server. The bot may contain \
        plugins that can easily cause quite a mess if placed in the hands of the wrong users.\n\nFirst things \
        first, heirarchy-based permissions for the bot are in 4 tiers:\n**Tier 1**: Regular users\n**Tier 2**: \
        Bot moderators (assigned by tier 3 or up)\n**Tier 3**: Server owners (also count as bot moderators)\n\
        **Tier 4**: Bot owners (access to debug commands)\n\nAs the server owner, you are essentially a bot \
        moderator that also has the ability to assign other users to be bot moderators. In addition to that, \
        you will also receive direct message notifications to any bot moderator activity (such as disabling \
        commands, muting channels, blocking users from bot interaction, etc.). **If you do not want to receive \
        these notifications, type `{invoker}owner notifications` in your server to disable them**."

      - "To see the commands that you can use as a server owner, see **`{invoker}help owner`**. Bot moderators \
        can do a variety of things as well that are arguably more important to making sure the bot is used how \
        you want it to be used. See **`{invoker}manual core 5`** and **`{invoker}help mod`** for that.\n\nLastly, \
        you also have access to the `{invoker}owner feedback <message>` command that allows you to send a message \
        to the bot owners. If you have any questions, suggestions, complaints, etc. you can use this to send \
        them."

  - - "Bot moderators"
    - - "As a bot moderator, you have a lot of control over what the bot can actually do, and who gets to use \
        the bot. To see a list of commands, see **`{invoker}help mod`**.\n\nHere are a few things you can do:\
        \n**Block users**: You can block users from using the bot. This is useful if the user is misuing the bot \
        or spamming commands.\n**Mute channels or the server**: The bot will not respond to commands by regular \
        users in a muted channel or server. Bot moderators ignore this, though. You can mute both voice and text \
        channels.\n**Set an invoker**: If there is another bot on the server, it might be possible that there is \
        an invoker collision. You can set a custom invoker for this bot to avoid conflict.\n**Disable commands**: \
        Sometimes a server could do better without a specific command. Disabling or enabling certain commands \
        allows you to fine-tune the functionality of the bot for the server. Note that like muting channels, bot \
        moderators can also use disabled commands."
    
      - "As you may know, there are a few other commands, but they are not as important. To get the general \
        information about a server (such as which users and channels are muted, whether mention mode is active \
        or not, etc.), use **`{invoker}mod info`**.\n\nOne last thing to consider is that you may also have \
        access to some other commands by external plugins. For example, if the tag plugin is being used, you \
        have the power to access private tags, and delete or edit them. **Use your elevated privileges \
        responsibly!**"

  - - "FAQ"
    - - "**Q**: The bot isn't responding to my commands!\n**A**: Make sure you aren't blocked from bot \
        interaction, and that the bot isn't muted in your channel, or even the entire server. To see if the bot \
        is alive and active, send it a direct message ping commad, `{base_invoker}ping`. Also, make sure you are \
        using the correct invoker for the server you are on. If you are a bot moderator, you can see if the bot \
        is using a custom invoker or has mention mode active with `{invoker}mod info`. An invoker that will \
        always work would be a mention to the bot."

      - "**Q**: There is too much spam. Is there a way to curb \
        that?\n**A**: There is a built in rate limit for commands that defaults to about 1 command per 3 seconds. \
        However, if you wanted to stop command spam, you can block users, mute channels, and even disable \
        commands (given that you are a bot moderator). See `{invoker}manual core 5` for more.\n\n**Q**: The sound \
        quality deteriorates sometimes. Why is that?\n**A**: This mostly depends on what hardware the bot is \
        running on and how many people are using sound related commands at the same time. If there are too many \
        people using sound commands at the same time, it can significantly slow down the bot. Also, server \
        location can play a role in quality, so keep that in mind.\n\n**Q**: Can I request a feature (or voice a \
        comment/complaint, etc.)?\n**A**: You can ask your server owner to use the `{invoker}owner feedback \
        <message>` command to send the bot owners a suggestion or two."
